easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Recipe
       - App\Entity\Ingredients
       - App\Entity\KitchenTools
       - App\Entity\Reviews
       - App\Entity\Steps
       - App\Entity\Tag
       - App\Entity\Units
       - App\Entity\User

